# Generated by Django 3.1.3 on 2020-11-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('your_todoer_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
    ]
